//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class abonents
    {
        public int id { get; set; }
        public string name { get; set; }
        public string lName { get; set; }
        public string login { get; set; }
        public string number { get; set; }
        public int idTarif { get; set; }
        public string avaluable { get; set; }
    
        public virtual Auth Auth { get; set; }
        public virtual tarifs tarifs { get; set; }
    }
}
