//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admins
    {
        public int idAdmin { get; set; }
        public string name { get; set; }
        public string lName { get; set; }
        public string login { get; set; }
    
        public virtual Auth Auth { get; set; }
    }
}
